apiVersion: v1
kind: ConfigMap
metadata:
  name: typeform-rag-config
data:
  settings.yaml: |
    data:
      plaintext_dir: "data/plaintext"
      processed_dir: "data/processed"
      raw_html_dir: "data/raw"
      chunk_size: 256
      chunk_overlap: 25
    pinecone:
      api_key: "YOUR_PINECONE_API_KEY"
      environment: "us-east-1"
      index_name: "typeform"
      metric: "cosine"
      dimension: 384
    embedding:
      model: "BAAI/bge-small-en-v1.5"
    LLM:
      model: "microsoft/Phi-3.5-mini-instruct"

  logging_config.yaml: |
    version: 1
    disable_existing_loggers: False
    formatters:
      detailed:
        format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detailed
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detailed
        filename: logs/app.log
        maxBytes: 10485760
        backupCount: 3
    loggers:
      "":
        level: DEBUG
        handlers: ["console", "file"]
        propagate: no
      "uvicorn":
        level: WARNING
        handlers: ["console"]
        propagate: no
