apiVersion: apps/v1
kind: Deployment
metadata:
  name: typeform-rag
spec:
  replicas: 2
  selector:
    matchLabels:
      app: typeform-rag
  template:
    metadata:
      labels:
        app: typeform-rag
    spec:
      containers:
        - name: api
          image: typeform-rag-chatbot:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SETTINGS_PATH
              value: /config/settings.yaml
            - name: LOGGING_CONFIG
              value: /config/logging_config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: typeform-rag-config
