version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760
    backupCount: 3

loggers:
  "":
    level: DEBUG
    handlers: ["console", "file"]
    propagate: no

  "uvicorn":
    level: WARNING
    handlers: ["console"]
    propagate: no
