# config/settings.yaml

data:
  plaintext_dir: "data/plaintext"
  processed_dir: "data/processed"
  raw_html_dir: "data/raw"
  chunk_size: 256
  chunk_overlap: 25

pinecone:
  api_key: "YOUR PINECONE KEY HERE"
  environment: "us-east-1"
  index_name: "typeform"
  metric: "cosine"
  dimension: 384

embedding:
  model: "BAAI/bge-small-en-v1.5"

LLM:
  model: "microsoft/Phi-3.5-mini-instruct"
